# Generated by Django 3.1.3 on 2020-11-24 05:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201123_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to=core.models.image_file_path),
        ),
    ]
